# Generated by Django 3.1.5 on 2021-01-17 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_review_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ratings',
        ),
        migrations.AddField(
            model_name='review',
            name='negative_feedback',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AMB', 'Ambiance'), ('ATMS', 'Atmosphere'), ('CLN', 'Cleanliness'), ('DNK', 'Drink'), ('ENT', 'Entertainment'), ('FD', 'Food'), ('QLTY', 'Quality'), ('SRV', 'Service'), ('SPD', 'Speed'), ('VAL', 'Value')], max_length=4), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='review',
            name='positive_feedback',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AMB', 'Ambiance'), ('ATMS', 'Atmosphere'), ('CLN', 'Cleanliness'), ('DNK', 'Drink'), ('ENT', 'Entertainment'), ('FD', 'Food'), ('QLTY', 'Quality'), ('SRV', 'Service'), ('SPD', 'Speed'), ('VAL', 'Value')], max_length=4), blank=True, null=True, size=None),
        ),
    ]
