# Generated by Django 3.1.5 on 2021-01-17 23:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210117_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='negative_feedback',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ATMS', 'Atmosphere'), ('CLN', 'Cleanliness'), ('DCR', 'Decor'), ('DNK', 'Drink'), ('ENT', 'Entertainment'), ('FD', 'Food'), ('QLTY', 'Quality'), ('SRV', 'Service'), ('SPD', 'Speed'), ('VAL', 'Value')], max_length=4), blank=True, null=True, size=None, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='positive_feedback',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ATMS', 'Atmosphere'), ('CLN', 'Cleanliness'), ('DCR', 'Decor'), ('DNK', 'Drink'), ('ENT', 'Entertainment'), ('FD', 'Food'), ('QLTY', 'Quality'), ('SRV', 'Service'), ('SPD', 'Speed'), ('VAL', 'Value')], max_length=4), blank=True, null=True, size=None, unique=True),
        ),
    ]
