# Generated by Django 3.1.5 on 2021-01-21 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20210118_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date review published'),
        ),
        migrations.AddField(
            model_name='review',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 1, 45, 28, 980300, tzinfo=utc), verbose_name='Visit date and time'),
        ),
    ]
