# Generated by Django 3.1.5 on 2021-01-22 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210121_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review_Record',
            new_name='Scorecard',
        ),
        migrations.AlterField(
            model_name='review',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 5, 33, 36, 343609, tzinfo=utc), verbose_name='Visit date and time'),
        ),
    ]
