# Generated by Django 3.1.5 on 2021-01-23 01:33

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210122_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='negative_feedback',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AT', 'Atmosphere'), ('CL', 'Cleanliness'), ('DE', 'Decor'), ('DR', 'Drink'), ('EN', 'Entertainment'), ('FO', 'Food'), ('QU', 'Quality'), ('SE', 'Service'), ('SP', 'Speed'), ('VA', 'Value')], max_length=4), blank=True, null=True, size=None, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='positive_feedback',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AT', 'Atmosphere'), ('CL', 'Cleanliness'), ('DE', 'Decor'), ('DR', 'Drink'), ('EN', 'Entertainment'), ('FO', 'Food'), ('QU', 'Quality'), ('SE', 'Service'), ('SP', 'Speed'), ('VA', 'Value')], max_length=4), blank=True, null=True, size=None, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 1, 33, 58, 981034, tzinfo=utc), verbose_name='Visit date and time'),
        ),
    ]
