# Generated by Django 3.1.5 on 2021-01-23 02:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20210123_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='negative_feedback',
        ),
        migrations.RemoveField(
            model_name='review',
            name='positive_feedback',
        ),
        migrations.AlterField(
            model_name='review',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 2, 48, 0, 456519, tzinfo=utc), verbose_name='Visit date and time'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atmosphere', models.BooleanField(null=True)),
                ('cleanliness', models.BooleanField(null=True)),
                ('decor', models.BooleanField(null=True)),
                ('drink', models.BooleanField(null=True)),
                ('entertainment', models.BooleanField(null=True)),
                ('food', models.BooleanField(null=True)),
                ('quality', models.BooleanField(null=True)),
                ('service', models.BooleanField(null=True)),
                ('speed', models.BooleanField(null=True)),
                ('value', models.BooleanField(null=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='places.review')),
            ],
        ),
    ]
