# Generated by Django 3.1.5 on 2021-01-24 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20210123_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_date',
        ),
        migrations.AlterField(
            model_name='review',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 6, 27, 48, 629526, tzinfo=utc), verbose_name='Visit date and time'),
        ),
    ]
