# Generated by Django 3.1.5 on 2021-01-27 01:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20210124_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 1, 48, 28, 315672, tzinfo=utc), verbose_name='Visit date and time'),
        ),
    ]
